$schema: https://raw.githubusercontent.com/thoughts-on-things/freelane-ci/main/schemas/freelane.schema.json
version: 1

providers:
  github:
    enabled: true

jobs:
  ci-linux:
    os: linux
    arch: x64
    providers: [github]
